/**
 * Photos for the restaurant & bar menu (public/images/menu/<itemId>.webp), with the
 * credit each free licence asks for. Generated from the photo sourcing run; the
 * seed and the menu_photos migration register them in the media library.
 */
export type MenuPhoto = {
  file: string; alt: string; creator: string; license: string; licenseUrl: string; sourcePage: string;
  /** exact = that very dish / brand; representative = the same kind of dish or drink. */
  match: "exact" | "representative";
};

export const MENU_PHOTOS: Record<string, MenuPhoto> = {
  "mi_breakfast_vegas_english_breakfast": { file: "/images/menu/mi_breakfast_vegas_english_breakfast.webp", alt: "Full English breakfast on a blue plate with fried eggs on toast, sausage, bacon, baked beans, grilled cherry tomatoes and mushrooms, with sliced toast on a wooden board", creator: "Andy Li", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourcePage: "https://commons.wikimedia.org/wiki/File:Full_English_-_The_Boudica_2025-05-15.jpg", match: "exact" },
  "mi_breakfast_omelette_toast": { file: "/images/menu/mi_breakfast_omelette_toast.webp", alt: "Golden herb omelette on a white plate with a sprig of flat-leaf parsley and a slice of toasted bread", creator: "Krzysztof Golik", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Omelette_with_bread_and_parsley_01.jpg", match: "exact" },
  "mi_breakfast_chapati_eggs": { file: "/images/menu/mi_breakfast_chapati_eggs.webp", alt: "Stack of soft chapatis beside a white bowl of halved boiled eggs in a tomato-onion sauce, garnished with mint", creator: "Samphotography", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Chapati_with_egg_roast.jpg", match: "representative" },
  "mi_breakfast_tea_coffee_standard": { file: "/images/menu/mi_breakfast_tea_coffee_standard.webp", alt: "Tea being poured from a white porcelain teapot into a white cup with a slice of lemon on a saucer", creator: "Suhyeon Choi", license: "CC0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Suhyeon_Choi_2017-01-19_(Unsplash).jpg", match: "exact" },
  "mi_starters_soups_fish_soup": { file: "/images/menu/mi_starters_soups_fish_soup.webp", alt: "Bowl of rich tomato fish soup with prawns, a mussel and chopped parsley on a speckled ceramic plate", creator: "Sergey A. Demidov", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:20250903_Bouillabaisse_in_Khimki.jpg", match: "exact" },
  "mi_starters_soups_bbq_or_spicy_chicken_wings": { file: "/images/menu/mi_starters_soups_bbq_or_spicy_chicken_wings.webp", alt: "Close-up of glazed, charred grilled chicken wings sprinkled with herbs on a white plate", creator: "Isaac Wedin", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/izik/3730021196/", match: "exact" },
  "mi_starters_soups_chicken_soup": { file: "/images/menu/mi_starters_soups_chicken_soup.webp", alt: "White square bowl of chicken soup with shredded chicken, egg noodles, carrots and peppers in clear broth", creator: "Alabama Extension", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourcePage: "https://commons.wikimedia.org/wiki/File:Ginger_Chicken_Soup_with_Vegetables_-_50408986928.jpg", match: "exact" },
  "mi_starters_soups_creamy_mushroom_soup": { file: "/images/menu/mi_starters_soups_creamy_mushroom_soup.webp", alt: "Cup of creamy mushroom soup topped with golden croutons and fresh chopped herbs on a white saucer", creator: "Tess Mattew", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourcePage: "https://commons.wikimedia.org/wiki/File:2020.10.19_Mushrooms_cream_soup.jpg", match: "exact" },
  "mi_starters_soups_chicken_spring_rolls": { file: "/images/menu/mi_starters_soups_chicken_spring_rolls.webp", alt: "Stack of golden fried chicken spring rolls on a white platter with a dish of sweet chilli sauce", creator: "stu_spivack", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/stuart_spivack/15187509898/", match: "exact" },
  "mi_local_favorites_nyama_choma_beef": { file: "/images/menu/mi_local_favorites_nyama_choma_beef.webp", alt: "Chunks of charcoal-grilled beef nyama choma piled on a barbecue grill", creator: "safaritravelplus", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourcePage: "https://commons.wikimedia.org/wiki/File:Nyama_choma_barbeque.jpg", match: "exact" },
  "mi_local_favorites_samaki_choma_grilled_fish": { file: "/images/menu/mi_local_favorites_samaki_choma_grilled_fish.webp", alt: "Whole grilled fish with a lemon wedge, lettuce and potatoes with greens on a white plate", creator: "Luca.favorido", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Grilled_fish_with_vegetables_and_lemon.jpg", match: "representative" },
  "mi_local_favorites_wali_fish_curry": { file: "/images/menu/mi_local_favorites_wali_fish_curry.webp", alt: "Fish curry in a rich red sauce garnished with fresh curry leaves, served in a traditional clay pot", creator: "prasad.om", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/43810986@N03/6079730453", match: "representative" },
  "mi_local_favorites_wali_chicken_curry": { file: "/images/menu/mi_local_favorites_wali_chicken_curry.webp", alt: "Chicken curry with a dome of steamed white rice, fresh coriander and salad in a blue-rimmed bowl", creator: "pelican", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/pelican/53853097358/", match: "exact" },
  "mi_local_favorites_roasted_banana_meat_ndizi_nyama": { file: "/images/menu/mi_local_favorites_roasted_banana_meat_ndizi_nyama.webp", alt: "Green bananas (matoke) and beef simmered in a rich tomato stew with carrots, with sauteed greens on the side", creator: "Bswitaba", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Matoke-Meat_Stew-Sukuma_Wiki.jpg", match: "exact" },
  "mi_local_favorites_ugali_beef_stew": { file: "/images/menu/mi_local_favorites_ugali_beef_stew.webp", alt: "Slices of ugali beside a rich saucy beef stew and fresh tomato-onion kachumbari on a square white plate", creator: "Superchilum", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Kenyan_beef_fry.jpg", match: "representative" },
  "mi_local_favorites_ugali_dagaa_sukuma_wiki": { file: "/images/menu/mi_local_favorites_ugali_dagaa_sukuma_wiki.webp", alt: "Ugali with crispy fried dagaa (omena) and sauteed dark leafy greens on a pale green plate", creator: "VictorOchieng", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Meal_of_Omena,_Vegetables_and_Ugali.jpg", match: "exact" },
  "mi_local_favorites_wali_na_maharagwe_rice_beans": { file: "/images/menu/mi_local_favorites_wali_na_maharagwe_rice_beans.webp", alt: "Fluffy white rice garnished with coriander beside slow-cooked kidney beans in a rich tomato sauce", creator: "Shreya151994", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Rajma_Chawal_by_Rama_Bhave.jpg", match: "representative" },
  "mi_main_courses_beef_steak_veg_pepper_sauce": { file: "/images/menu/mi_main_courses_beef_steak_veg_pepper_sauce.webp", alt: "Grilled beef steak on a white plate with a jug of pepper gravy, mashed potatoes and a colourful vegetable salad", creator: "PattayaPatrol", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:DFC_2288_Juicy_grilled_steak_with_creamy_mashed_potatoes_and_a_colorful_garden_salad_served_with_rich_gravy_on_the_side.jpg", match: "exact" },
  "mi_main_courses_grilled_chicken_with_chips_or_veg": { file: "/images/menu/mi_main_courses_grilled_chicken_with_chips_or_veg.webp", alt: "Golden grilled chicken leg with carrots, asparagus and herbs over a smooth purée", creator: "Shixart1985", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Grilled_chicken_served_with_creamy_mashed_potatoes_and_fresh_vegetables_undefined.jpg", match: "exact" },
  "mi_main_courses_chicken_biryani": { file: "/images/menu/mi_main_courses_chicken_biryani.webp", alt: "Chicken biryani topped with fried onions in a copper handi, served with raita and curry", creator: "Dheerajk88", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Chicken_Hyderabadi_Biryani.JPG", match: "exact" },
  "mi_main_courses_fish_chips": { file: "/images/menu/mi_main_courses_fish_chips.webp", alt: "Large golden battered fish fillet over thin-cut chips on a grey plate with a pot of tartare sauce, a lemon wedge and mixed salad leaves, on a sunlit wooden table", creator: "Bahnfrend", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Fish_%26_Chips,_Gage_Roads_Freo,_2026_(01).jpg", match: "exact" },
  "mi_main_courses_chicken_rice_bowl": { file: "/images/menu/mi_main_courses_chicken_rice_bowl.webp", alt: "Glazed chargrilled chicken pieces with golden yellow rice, asparagus, broccoli and carrots on a black-and-white patterned plate, seen from above on a wooden table", creator: "Wilfredor", license: "CC0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Fried_chicken_with_vegetables_and_rice.jpg", match: "representative" },
  "mi_main_courses_chicken_pilau_beef_pilau": { file: "/images/menu/mi_main_courses_chicken_pilau_beef_pilau.webp", alt: "Spiced chicken pilau with a cinnamon stick and fresh herbs on a white plate", creator: "Alpha (avlxyz)", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/avlxyz/4684623071/", match: "representative" },
  "mi_main_courses_beef_burger": { file: "/images/menu/mi_main_courses_beef_burger.webp", alt: "Beef cheeseburger with lettuce, tomato and red onion in a sesame bun, served with waffle fries on a white plate", creator: "TheCulinaryGeek", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/preppybyday/5076301075/", match: "exact" },
  "mi_main_courses_spaghetti_bolognese": { file: "/images/menu/mi_main_courses_spaghetti_bolognese.webp", alt: "Close-up of spaghetti topped with rich beef bolognese sauce and fresh basil leaves", creator: "Toshiyuki IMAI (matsuyuki)", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/matsuyuki/11267496906/", match: "exact" },
  "mi_main_courses_french_fries": { file: "/images/menu/mi_main_courses_french_fries.webp", alt: "Crisp golden french fries sprinkled with chopped parsley", creator: "Tony Webster", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Truffle_oil_french_fries_(33024792848).jpg", match: "exact" },
  "mi_main_courses_fried_rice": { file: "/images/menu/mi_main_courses_fried_rice.webp", alt: "Bowl of egg fried rice with green peas and diced carrot", creator: "Guilhem Vellut", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Cantonese_Rice_@_Porte_du_Bonheur_@_Montparnasse_@_Paris_(33894665242).jpg", match: "exact" },
  "mi_main_courses_ugali_extra_portion": { file: "/images/menu/mi_main_courses_ugali_extra_portion.webp", alt: "Two smooth white scoops of ugali (stiff maize porridge) beside sauteed leafy greens on a white plate, set on a dark woven placemat with a fork and knife", creator: "Marcel.blankenstein", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Nsima_and_Relish.jpg", match: "exact" },
  "mi_sides_drinks_fresh_fruit_smoothies": { file: "/images/menu/mi_sides_drinks_fresh_fruit_smoothies.webp", alt: "Glass of green kiwi smoothie topped with a mint sprig, with halved kiwi fruit on a wooden board", creator: "rawpixel.com", license: "CC0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Kiwi_Smoothie.jpg", match: "exact" },
  "mi_sides_drinks_fresh_assorted_juices": { file: "/images/menu/mi_sides_drinks_fresh_assorted_juices.webp", alt: "Glass of fresh passion fruit juice with seeds and crushed ice, garnished with mint, halved passion fruit and lime behind", creator: "rawpixel.com", license: "CC0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Suco_de_maracuj%C3%A1_1.jpg", match: "exact" },
  "mi_sides_drinks_soda_cold_soft_drink": { file: "/images/menu/mi_sides_drinks_soda_cold_soft_drink.webp", alt: "Chilled glass of cola with ice cubes and lemon slices on a plain light background", creator: "pic_p_ter", license: "Public domain", licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Glass_cola.jpg", match: "exact" },
  "mi_sides_drinks_mineral_water": { file: "/images/menu/mi_sides_drinks_mineral_water.webp", alt: "Clear still water pouring from an unlabelled bottle into a glass against a dark blue background", creator: "rawpixel.com (photographer not credited)", license: "CC0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", sourcePage: "https://www.rawpixel.com/image/5970544/mineral-water-drink", match: "exact" },
  "mi_beers_safari": { file: "/images/menu/mi_beers_safari.webp", alt: "Two frosty pint glasses of golden lager with foamy heads on a bar counter", creator: "Wagner T. Cassimiro \"Aranha\"", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/38469672@N00/4800234604", match: "representative" },
  "mi_beers_kilimanjaro": { file: "/images/menu/mi_beers_kilimanjaro.webp", alt: "Frosty glass of Kilimanjaro Premium Lager with a thick white head and the brand logo on the glass", creator: "Dan arndt", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Kilimanjaro_Premium_Lager.jpg", match: "exact" },
  "mi_beers_castle_lager": { file: "/images/menu/mi_beers_castle_lager.webp", alt: "Frosty pint glass of Castle Lager with a foamy head on a veranda overlooking green bushveld", creator: "Bernard DUPONT", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/65695019@N07/54172948727", match: "exact" },
  "mi_beers_castle_lite": { file: "/images/menu/mi_beers_castle_lite.webp", alt: "Chilled glass of Castle Lite beer with a foamy head under a thatched shade", creator: "Bernard DUPONT", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/berniedup/54080660008/", match: "exact" },
  "mi_beers_serengeti_lite": { file: "/images/menu/mi_beers_serengeti_lite.webp", alt: "Two glasses of pale golden light beer with foamy heads beside a bowl of hazelnuts on a wooden table", creator: "Didriks", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/49889671@N03/7693255346", match: "representative" },
  "mi_beers_flying_fish": { file: "/images/menu/mi_beers_flying_fish.webp", alt: "Tall glass of chilled golden beer with a thick foamy head against a soft-focus sunny terrace", creator: "martingarri", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/38001453@N00/7303114160", match: "representative" },
  "mi_beers_kili_lager": { file: "/images/menu/mi_beers_kili_lager.webp", alt: "Chilled pint glass of golden lager with a thick white head on a light wooden bar top", creator: "cogdogblog", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/37996646802@N01/21127813750", match: "representative" },
  "mi_beers_heineken": { file: "/images/menu/mi_beers_heineken.webp", alt: "Full, frosty Heineken-branded mug of golden lager on a ledge against a soft-focus sunny beach", creator: "md-2", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/52818207@N00/2742187636", match: "exact" },
  "mi_beers_windhoek": { file: "/images/menu/mi_beers_windhoek.webp", alt: "Green 330 ml bottle of Windhoek Premium Lager against a brushed metal background", creator: "Ji-Elle", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Bi%C3%A8re_de_Namibie-Windhoek_Lager.jpg", match: "exact" },
  "mi_beers_desperado": { file: "/images/menu/mi_beers_desperado.webp", alt: "Close-up of the label on a bottle of Desperados tequila-flavoured beer", creator: "Ben Sutherland", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/bensutherland/5488172521/", match: "exact" },
  "mi_beers_savana": { file: "/images/menu/mi_beers_savana.webp", alt: "Two bottles of Savanna Light premium cider standing in golden sand at sunset", creator: "Hp.Baumeler", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Savanna_Light.jpg", match: "exact" },
  "mi_wines_st_anna": { file: "/images/menu/mi_wines_st_anna.webp", alt: "Glass of red wine on a clean light background", creator: "Davide Restivo", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:A_glass_of_red_wine.jpg", match: "representative" },
  "mi_wines_robertson_white": { file: "/images/menu/mi_wines_robertson_white.webp", alt: "Chilled glass of white wine with condensation against a warm, softly blurred background", creator: "Robert S. Donovan", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:A_glass_of_Chablis.jpg", match: "representative" },
  "mi_wines_robertson_red": { file: "/images/menu/mi_wines_robertson_red.webp", alt: "Bottle of red wine beside a full glass of red wine on a dark background", creator: "congerdesign", license: "CC0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Bottle_and_glass_of_red_wine.jpg", match: "representative" },
  "mi_wines_drostdyhof_red_750ml": { file: "/images/menu/mi_wines_drostdyhof_red_750ml.webp", alt: "Bottle of Drostdy-Hof Cabernet Sauvignon red wine lying on a warm wooden table", creator: "Shunichi kouroki (kohrogi34)", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/kohrogi/8253449077/", match: "exact" },
  "mi_wines_drostdyhof_red_375ml": { file: "/images/menu/mi_wines_drostdyhof_red_375ml.webp", alt: "Bottle of Drostdy-Hof Cabernet Sauvignon red wine lying on a warm wooden table", creator: "Shunichi kouroki (kohrogi34)", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/kohrogi/8253449077/", match: "exact" },
  "mi_wines_drostdyhof_white_750ml": { file: "/images/menu/mi_wines_drostdyhof_white_750ml.webp", alt: "Glass of chilled white wine on a restaurant table beside a glass of iced water", creator: "Jon Sullivan", license: "Public domain", licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Glass_of_white_wine.jpg", match: "representative" },
  "mi_wines_drostdyhof_white_375ml": { file: "/images/menu/mi_wines_drostdyhof_white_375ml.webp", alt: "Glass of chilled white wine on a restaurant table beside a glass of iced water", creator: "Jon Sullivan", license: "Public domain", licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Glass_of_white_wine.jpg", match: "representative" },
  "mi_wines_altar_wine": { file: "/images/menu/mi_wines_altar_wine.webp", alt: "Glass of deep ruby sweet red wine beside raspberries and red grapes on a glossy black surface", creator: "Nonnoant", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Deep_ruby_red_color,_the_characteristics_of_Moscato_di_Scanzo.jpg", match: "representative" },
  "mi_wines_pearly_bay_dry_rose": { file: "/images/menu/mi_wines_pearly_bay_dry_rose.webp", alt: "Glass of pale dry rosé wine on a bright turquoise table beside potted flowers", creator: "Sarah Stierch (Missvain)", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Ros%C3%A9_wine_-_July_2023_-_Sarah_Stierch_01.jpg", match: "representative" },
  "mi_wines_pearly_bay_sweet": { file: "/images/menu/mi_wines_pearly_bay_sweet.webp", alt: "Chilled bottle of pink rosé wine with condensation beside a filled wine glass on a white background", creator: "THOR", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Sancerre_rose_Wine.jpg", match: "representative" },
  "mi_wines_lion_hill": { file: "/images/menu/mi_wines_lion_hill.webp", alt: "Red wine being poured from a bottle into a wine glass against a soft green background", creator: "Bhullargraphic", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Close-up_of_red_wine_being_poured_into_a_glass_with_a_blurred_outdoor_backdrop.jpg", match: "representative" },
  "mi_wines_four_cousin": { file: "/images/menu/mi_wines_four_cousin.webp", alt: "Close-up of a glass of red wine against a soft colourful bokeh background", creator: "Etwood", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/44788018@N00/2874891036", match: "representative" },
  "mi_wines_bonne_esperance": { file: "/images/menu/mi_wines_bonne_esperance.webp", alt: "Overhead view of a red wine bottle and a glass of red wine on a grey stone surface", creator: "Shixart1985", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Red_wine_bottle_and_glass_on_a_gray_surface_during_an_evening_gathering.jpg", match: "representative" },
  "mi_wines_dodoma_wine": { file: "/images/menu/mi_wines_dodoma_wine.webp", alt: "Glass of red wine glowing against a golden sunset", creator: "Glorious 93", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Glass_of_wine_at_Manali_Winery,_Sikinos.jpg", match: "representative" },
  "mi_wines_dompo": { file: "/images/menu/mi_wines_dompo.webp", alt: "Red wine being poured from a bottle into a large wine glass against a soft bokeh background", creator: "Rawpixel Ltd", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/147875007@N03/31917917488", match: "representative" },
  "mi_wines_champaign_pearly_bay": { file: "/images/menu/mi_wines_champaign_pearly_bay.webp", alt: "Sparkling wine being poured from a green bottle into two bubbling flutes in warm light", creator: "Quinn Dombrowski", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Pouring_two_champagne_glasses.jpg", match: "representative" },
  "mi_wines_mohans": { file: "/images/menu/mi_wines_mohans.webp", alt: "Glass of red wine glowing in warm candlelight with tea lights in the background", creator: "quacktaculous", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/27496606@N08/3020750515", match: "representative" },
  "mi_whiskies_jameson_750ml": { file: "/images/menu/mi_whiskies_jameson_750ml.webp", alt: "Bottle of Jameson Irish Whiskey against a deep green backdrop", creator: "Jennifercrowley", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:50752085_HEROSHOT.jpg", match: "exact" },
  "mi_whiskies_jameson_500ml": { file: "/images/menu/mi_whiskies_jameson_500ml.webp", alt: "Bottle of Jameson Irish Whiskey against a deep green backdrop", creator: "Jennifercrowley", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:50752085_HEROSHOT.jpg", match: "exact" },
  "mi_whiskies_jameson_250ml": { file: "/images/menu/mi_whiskies_jameson_250ml.webp", alt: "Bottle of Jameson Irish Whiskey against a deep green backdrop", creator: "Jennifercrowley", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:50752085_HEROSHOT.jpg", match: "exact" },
  "mi_whiskies_grants_750ml": { file: "/images/menu/mi_whiskies_grants_750ml.webp", alt: "Row of Grant's blended Scotch whisky bottles, including Family Reserve, on a white background", creator: "William Grant & Sons Ltd", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourcePage: "https://commons.wikimedia.org/wiki/File:Full_Range_Grant%27s_Whisky.jpg", match: "exact" },
  "mi_whiskies_grants_500ml": { file: "/images/menu/mi_whiskies_grants_500ml.webp", alt: "Row of Grant's blended Scotch whisky bottles, including Family Reserve, on a white background", creator: "William Grant & Sons Ltd", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourcePage: "https://commons.wikimedia.org/wiki/File:Full_Range_Grant%27s_Whisky.jpg", match: "exact" },
  "mi_whiskies_ballantine_750ml": { file: "/images/menu/mi_whiskies_ballantine_750ml.webp", alt: "Bottle of Ballantine's Finest blended Scotch whisky beside a tumbler of whisky on a white background", creator: "Jacek Halicki", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:2017_Ballantine%27s_Finest.jpg", match: "exact" },
  "mi_whiskies_ballantine_250ml": { file: "/images/menu/mi_whiskies_ballantine_250ml.webp", alt: "Bottle of Ballantine's Finest blended Scotch whisky beside a tumbler of whisky on a white background", creator: "Jacek Halicki", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:2017_Ballantine%27s_Finest.jpg", match: "exact" },
  "mi_whiskies_jack_daniels_750ml": { file: "/images/menu/mi_whiskies_jack_daniels_750ml.webp", alt: "Bottle of Jack Daniel's Old No. 7 Tennessee whiskey next to a glass of whiskey on the rocks", creator: "Caitlinator", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/21484712@N00/2846354345", match: "exact" },
  "mi_whiskies_jack_daniels_500ml": { file: "/images/menu/mi_whiskies_jack_daniels_500ml.webp", alt: "Bottle of Jack Daniel's Old No. 7 Tennessee whiskey next to a glass of whiskey on the rocks", creator: "Caitlinator", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/21484712@N00/2846354345", match: "exact" },
  "mi_whiskies_jack_daniels_250ml": { file: "/images/menu/mi_whiskies_jack_daniels_250ml.webp", alt: "Bottle of Jack Daniel's Old No. 7 Tennessee whiskey next to a glass of whiskey on the rocks", creator: "Caitlinator", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", sourcePage: "https://www.flickr.com/photos/21484712@N00/2846354345", match: "exact" },
  "mi_whiskies_red_label_750ml": { file: "/images/menu/mi_whiskies_red_label_750ml.webp", alt: "Bottle of Johnnie Walker Red Label blended Scotch whisky on a wooden surface", creator: "Indrajit Das", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Johnnie_Walker_Red_Label_Blended_Scotch_Whisky_02.jpg", match: "exact" },
  "mi_whiskies_red_label_250ml": { file: "/images/menu/mi_whiskies_red_label_250ml.webp", alt: "Bottle of Johnnie Walker Red Label blended Scotch whisky on a wooden surface", creator: "Indrajit Das", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Johnnie_Walker_Red_Label_Blended_Scotch_Whisky_02.jpg", match: "exact" },
  "mi_whiskies_black_label_750ml": { file: "/images/menu/mi_whiskies_black_label_750ml.webp", alt: "Bottle of Johnnie Walker Black Label 12-year-old blended Scotch whisky beside its black gift box", creator: "Iceman7840", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", sourcePage: "https://commons.wikimedia.org/wiki/File:Johnnie_Walker_Black_Label.jpg", match: "exact" },
  "mi_whiskies_black_white_750ml": { file: "/images/menu/mi_whiskies_black_white_750ml.webp", alt: "Scotch on the rocks in a tumbler with a water chaser on a polished bar counter, warm backlit shelves behind", creator: "Ka23 13", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Kokura_20180101_213836.jpg", match: "representative" },
  "mi_whiskies_black_white_250ml": { file: "/images/menu/mi_whiskies_black_white_250ml.webp", alt: "Scotch on the rocks in a tumbler with a water chaser on a polished bar counter, warm backlit shelves behind", creator: "Ka23 13", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Kokura_20180101_213836.jpg", match: "representative" },
  "mi_spirits_jagermeister_1l": { file: "/images/menu/mi_spirits_jagermeister_1l.webp", alt: "Bottle of Jägermeister herbal liqueur beside two etched shot glasses", creator: "Webscribe", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:J%C3%A4germeister_with_shot_glasses.jpg", match: "exact" },
  "mi_spirits_jagermeister_750ml": { file: "/images/menu/mi_spirits_jagermeister_750ml.webp", alt: "Bottle of Jägermeister herbal liqueur beside two etched shot glasses", creator: "Webscribe", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:J%C3%A4germeister_with_shot_glasses.jpg", match: "exact" },
  "mi_spirits_jagermeister_500ml": { file: "/images/menu/mi_spirits_jagermeister_500ml.webp", alt: "Bottle of Jägermeister herbal liqueur beside two etched shot glasses", creator: "Webscribe", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:J%C3%A4germeister_with_shot_glasses.jpg", match: "exact" },
  "mi_spirits_jagermeister_250ml": { file: "/images/menu/mi_spirits_jagermeister_250ml.webp", alt: "Bottle of Jägermeister herbal liqueur beside two etched shot glasses", creator: "Webscribe", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:J%C3%A4germeister_with_shot_glasses.jpg", match: "exact" },
  "mi_spirits_hennessy_750ml": { file: "/images/menu/mi_spirits_hennessy_750ml.webp", alt: "Bottle of Hennessy Very Special cognac with a small crystal glass of cognac on a white background", creator: "Jacek Halicki", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:2023_Hennessy_V.S._Cognac.jpg", match: "exact" },
  "mi_spirits_hennessy_500ml": { file: "/images/menu/mi_spirits_hennessy_500ml.webp", alt: "Bottle of Hennessy Very Special cognac with a small crystal glass of cognac on a white background", creator: "Jacek Halicki", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:2023_Hennessy_V.S._Cognac.jpg", match: "exact" },
  "mi_spirits_hennessy_250ml": { file: "/images/menu/mi_spirits_hennessy_250ml.webp", alt: "Bottle of Hennessy Very Special cognac with a small crystal glass of cognac on a white background", creator: "Jacek Halicki", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:2023_Hennessy_V.S._Cognac.jpg", match: "exact" },
  "mi_spirits_k_vant_750ml": { file: "/images/menu/mi_spirits_k_vant_750ml.webp", alt: "Gin and tonic with ice and lime, with a dry gin bottle and lime wedges behind it", creator: "NotFromUtrecht", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Gin_and_Tonic_with_ingredients.jpg", match: "representative" },
  "mi_spirits_k_vant_250ml": { file: "/images/menu/mi_spirits_k_vant_250ml.webp", alt: "Gin and tonic with ice and lime, with a dry gin bottle and lime wedges behind it", creator: "NotFromUtrecht", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Gin_and_Tonic_with_ingredients.jpg", match: "representative" },
  "mi_spirits_smirnoff_750ml": { file: "/images/menu/mi_spirits_smirnoff_750ml.webp", alt: "Bottle of Smirnoff No. 21 Red Label vodka against a pale studio background", creator: "Ashley Pomeroy", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Smirnoff_Red_Label_8213.jpg", match: "exact" },
  "mi_spirits_smirnoff_250ml": { file: "/images/menu/mi_spirits_smirnoff_250ml.webp", alt: "Bottle of Smirnoff No. 21 Red Label vodka against a pale studio background", creator: "Ashley Pomeroy", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Smirnoff_Red_Label_8213.jpg", match: "exact" },
  "mi_spirits_gordons_750ml": { file: "/images/menu/mi_spirits_gordons_750ml.webp", alt: "Bottle of Gordon's London Dry Gin beside a glass of gin and tonic with ice and a lemon slice", creator: "StevenBrace", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Gordon%27s_Gin_2.jpg", match: "exact" },
  "mi_spirits_gordons_250ml": { file: "/images/menu/mi_spirits_gordons_250ml.webp", alt: "Bottle of Gordon's London Dry Gin beside a glass of gin and tonic with ice and a lemon slice", creator: "StevenBrace", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Gordon%27s_Gin_2.jpg", match: "exact" },
  "mi_spirits_absolute_vodka_750ml": { file: "/images/menu/mi_spirits_absolute_vodka_750ml.webp", alt: "Several Absolut Vodka bottles of different sizes lit against a green backdrop", creator: "Edward Cwik", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Absolut_Vodka_(Blue).JPG", match: "exact" },
  "mi_spirits_absolute_vodka_500ml": { file: "/images/menu/mi_spirits_absolute_vodka_500ml.webp", alt: "Several Absolut Vodka bottles of different sizes lit against a green backdrop", creator: "Edward Cwik", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Absolut_Vodka_(Blue).JPG", match: "exact" },
  "mi_spirits_absolute_vodka_250ml": { file: "/images/menu/mi_spirits_absolute_vodka_250ml.webp", alt: "Several Absolut Vodka bottles of different sizes lit against a green backdrop", creator: "Edward Cwik", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Absolut_Vodka_(Blue).JPG", match: "exact" },
  "mi_spirits_jb_750ml": { file: "/images/menu/mi_spirits_jb_750ml.webp", alt: "Two tumblers of Scotch whisky over large ice cubes on a dark wooden bar top", creator: "Personal Creations", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Giant_ice_cube_in_whiskey_glass_(18495546988).jpg", match: "representative" },
  "mi_spirits_jb_250ml": { file: "/images/menu/mi_spirits_jb_250ml.webp", alt: "Two tumblers of Scotch whisky over large ice cubes on a dark wooden bar top", creator: "Personal Creations", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Giant_ice_cube_in_whiskey_glass_(18495546988).jpg", match: "representative" },
  "mi_spirits_hanson_choice_750ml": { file: "/images/menu/mi_spirits_hanson_choice_750ml.webp", alt: "Brandy snifter with a pour of amber brandy against a black background", creator: "Didier Descouens", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Cognac_glass.jpg", match: "representative" },
  "mi_spirits_hanson_choice_250ml": { file: "/images/menu/mi_spirits_hanson_choice_250ml.webp", alt: "Brandy snifter with a pour of amber brandy against a black background", creator: "Didier Descouens", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Cognac_glass.jpg", match: "representative" },
  "mi_spirits_camino": { file: "/images/menu/mi_spirits_camino.webp", alt: "Chilled shots of gold tequila in blue-rimmed Mexican shot glasses on a polished wooden bar, with a lime wedge and a glass of salt", creator: "KittyKaht", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", sourcePage: "https://www.flickr.com/photos/78962213@N00/6183214000", match: "representative" },
  "mi_spirits_amarula_500ml": { file: "/images/menu/mi_spirits_amarula_500ml.webp", alt: "Bottle of Amarula Cream liqueur with its elephant label against a warm orange wall", creator: "SpesBona", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Amarula_Cream.jpg", match: "exact" },
  "mi_spirits_amarula_750ml": { file: "/images/menu/mi_spirits_amarula_750ml.webp", alt: "Bottle of Amarula Cream liqueur with its elephant label against a warm orange wall", creator: "SpesBona", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Amarula_Cream.jpg", match: "exact" },
  "mi_spirits_amarula_250ml": { file: "/images/menu/mi_spirits_amarula_250ml.webp", alt: "Bottle of Amarula Cream liqueur with its elephant label against a warm orange wall", creator: "SpesBona", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourcePage: "https://commons.wikimedia.org/wiki/File:Amarula_Cream.jpg", match: "exact" },
};

/**
 * The hotel's own product photos (public/images/menu/supplied/), used instead of a
 * free photo when the hotel has the real bottle shot. No outside credit needed.
 * One file can serve several sizes of the same drink.
 */
export type SuppliedPhoto = { file: string; alt: string; mediaId: string };
export const SUPPLIED_MENU_PHOTOS: Record<string, SuppliedPhoto> = {
  mi_spirits_konyagi_750ml: { file: "/images/menu/supplied/konyagi.webp", alt: "Two bottles of Konyagi, the spirit of Africa, with the yellow and gold label", mediaId: "media_supplied_konyagi" },
  mi_spirits_konyagi_500ml: { file: "/images/menu/supplied/konyagi.webp", alt: "Two bottles of Konyagi, the spirit of Africa, with the yellow and gold label", mediaId: "media_supplied_konyagi" },
  mi_spirits_konyagi_250ml: { file: "/images/menu/supplied/konyagi.webp", alt: "Two bottles of Konyagi, the spirit of Africa, with the yellow and gold label", mediaId: "media_supplied_konyagi" },
  mi_beers_brutal: { file: "/images/menu/supplied/brutal-fruit.webp", alt: "Chilled bottle of Brutal Fruit Cider, Ruby Apple", mediaId: "media_supplied_brutal_fruit" },
};

/** Credit lookup by the photo's public path. */
export const MENU_PHOTO_BY_FILE = new Map(Object.values(MENU_PHOTOS).map((p) => [p.file, p]));
