/**
 * The hotel's restaurant & bar menu as first loaded (the restaurant_bar migration inserts the
 * same rows). After that the menu lives in the database and is edited in
 * Staff → Restaurant & bar → Menu — pages never hard-code prices.
 */
export const MENU_CATALOG: {
  id: string; name: string; slug: string; type: "FOOD" | "DRINK"; revenueKind: "RESTAURANT" | "BAR"; description: string | null;
  items: { id: string; name: string; description: string | null; price: number; subcategory: string | null }[];
}[] = [
  { id: "mcat_breakfast", name: "Breakfast", slug: "breakfast", type: "FOOD", revenueKind: "RESTAURANT", description: "Served every morning — hearty, fresh and made to order.", items: [
    { id: "mi_breakfast_vegas_english_breakfast", name: "Vegas English Breakfast", description: "Eggs your way, sausages, grilled tomato, beans, toast and tea or coffee.", price: 9000, subcategory: null },
    { id: "mi_breakfast_omelette_toast", name: "Omelette & Toast", description: "A fluffy three-egg omelette with buttered toast.", price: 6000, subcategory: null },
    { id: "mi_breakfast_chapati_eggs", name: "Chapati & Eggs", description: "Soft home-made chapati with fried or scrambled eggs.", price: 4000, subcategory: null },
    { id: "mi_breakfast_tea_coffee_standard", name: "Tea/Coffee (Standard)", description: "A pot of local tea or freshly brewed coffee.", price: 3000, subcategory: null },
  ] },
  { id: "mcat_starters_soups", name: "Starters & Soups", slug: "starters-soups", type: "FOOD", revenueKind: "RESTAURANT", description: "Something light to begin.", items: [
    { id: "mi_starters_soups_fish_soup", name: "Fish Soup", description: "Rich coastal fish soup with fresh herbs and lime.", price: 22000, subcategory: null },
    { id: "mi_starters_soups_bbq_or_spicy_chicken_wings", name: "BBQ or Spicy Chicken Wings", description: "Crispy wings, glazed BBQ or tossed in pili-pili.", price: 7000, subcategory: null },
    { id: "mi_starters_soups_chicken_soup", name: "Chicken Soup", description: "Slow-simmered chicken broth with vegetables.", price: 5000, subcategory: null },
    { id: "mi_starters_soups_creamy_mushroom_soup", name: "Creamy Mushroom Soup", description: "Velvety mushroom soup, finished with cream.", price: 5000, subcategory: null },
    { id: "mi_starters_soups_chicken_spring_rolls", name: "Chicken Spring Rolls", description: "Golden rolls filled with spiced chicken and vegetables.", price: 5000, subcategory: null },
  ] },
  { id: "mcat_local_favorites", name: "Local Favorites", slug: "local-favorites", type: "FOOD", revenueKind: "RESTAURANT", description: "The taste of Tanzania, cooked the way it should be.", items: [
    { id: "mi_local_favorites_nyama_choma_beef", name: "Nyama Choma (Beef)", description: "Charcoal-grilled beef, served with kachumbari and your choice of side.", price: 22000, subcategory: null },
    { id: "mi_local_favorites_samaki_choma_grilled_fish", name: "Samaki Choma (Grilled Fish)", description: "Whole fish grilled over charcoal with lemon and spices.", price: 20000, subcategory: null },
    { id: "mi_local_favorites_wali_fish_curry", name: "Wali Fish Curry", description: "Coconut fish curry served with steamed rice.", price: 9000, subcategory: null },
    { id: "mi_local_favorites_wali_chicken_curry", name: "Wali Chicken Curry", description: "Tender chicken curry served with steamed rice.", price: 9000, subcategory: null },
    { id: "mi_local_favorites_roasted_banana_meat_ndizi_nyama", name: "Roasted Banana & Meat (Ndizi Nyama)", description: "Green bananas slow-cooked with beef in a savoury sauce.", price: 8500, subcategory: null },
    { id: "mi_local_favorites_ugali_beef_stew", name: "Ugali & Beef Stew", description: "Classic ugali with a rich beef stew.", price: 8500, subcategory: null },
    { id: "mi_local_favorites_ugali_dagaa_sukuma_wiki", name: "Ugali, Dagaa & Sukuma Wiki", description: "Ugali with fried dagaa and sautéed greens.", price: 7000, subcategory: null },
    { id: "mi_local_favorites_wali_na_maharagwe_rice_beans", name: "Wali na Maharagwe (Rice & Beans)", description: "Coconut rice with slow-cooked beans.", price: 6000, subcategory: null },
  ] },
  { id: "mcat_main_courses", name: "Main Courses", slug: "main-courses", type: "FOOD", revenueKind: "RESTAURANT", description: "Signature plates from our kitchen.", items: [
    { id: "mi_main_courses_beef_steak_veg_pepper_sauce", name: "Beef Steak (Veg & Pepper Sauce)", description: "Grilled beef steak with seasonal vegetables and pepper sauce.", price: 18000, subcategory: null },
    { id: "mi_main_courses_grilled_chicken_with_chips_or_veg", name: "Grilled Chicken (with Chips or Veg)", description: "Marinated grilled chicken with chips or vegetables.", price: 12000, subcategory: null },
    { id: "mi_main_courses_chicken_biryani", name: "Chicken Biryani", description: "Fragrant spiced rice layered with tender chicken.", price: 12000, subcategory: null },
    { id: "mi_main_courses_fish_chips", name: "Fish & Chips", description: "Crispy battered fish with golden chips and tartare sauce.", price: 11000, subcategory: null },
    { id: "mi_main_courses_chicken_rice_bowl", name: "Chicken Rice Bowl", description: "Seasoned chicken over rice with fresh vegetables.", price: 11000, subcategory: null },
    { id: "mi_main_courses_chicken_pilau_beef_pilau", name: "Chicken Pilau / Beef Pilau", description: "Swahili spiced pilau with chicken or beef.", price: 10000, subcategory: null },
    { id: "mi_main_courses_beef_burger", name: "Beef Burger", description: "Juicy beef patty, cheese and fresh salad in a toasted bun.", price: 9000, subcategory: null },
    { id: "mi_main_courses_spaghetti_bolognese", name: "Spaghetti Bolognese", description: "Spaghetti with a slow-cooked beef and tomato sauce.", price: 9000, subcategory: null },
    { id: "mi_main_courses_french_fries", name: "French Fries", description: "Crisp golden fries.", price: 8000, subcategory: null },
    { id: "mi_main_courses_fried_rice", name: "Fried Rice", description: "Wok-fried rice with vegetables and egg.", price: 5000, subcategory: null },
    { id: "mi_main_courses_ugali_extra_portion", name: "Ugali (Extra Portion)", description: "An extra portion of ugali.", price: 3000, subcategory: null },
  ] },
  { id: "mcat_sides_drinks", name: "Sides & Drinks", slug: "sides-drinks", type: "DRINK", revenueKind: "RESTAURANT", description: "Fresh, cold and non-alcoholic.", items: [
    { id: "mi_sides_drinks_fresh_fruit_smoothies", name: "Fresh Fruit Smoothies", description: "Blended seasonal fruit.", price: 5000, subcategory: "Soft drink" },
    { id: "mi_sides_drinks_fresh_assorted_juices", name: "Fresh Assorted Juices", description: "Pressed daily — mango, passion, pineapple or watermelon.", price: 4000, subcategory: "Soft drink" },
    { id: "mi_sides_drinks_soda_cold_soft_drink", name: "Soda (Cold Soft Drink)", description: "Your choice of chilled soft drink.", price: 2500, subcategory: "Soft drink" },
    { id: "mi_sides_drinks_mineral_water", name: "Mineral Water", description: "Chilled bottled water.", price: 1500, subcategory: "Soft drink" },
  ] },
  { id: "mcat_beers", name: "Beers", slug: "beers", type: "DRINK", revenueKind: "BAR", description: "Ice-cold local and international beers.", items: [
    { id: "mi_beers_safari", name: "Safari", description: null, price: 4000, subcategory: "Beer" },
    { id: "mi_beers_kilimanjaro", name: "Kilimanjaro", description: null, price: 4000, subcategory: "Beer" },
    { id: "mi_beers_castle_lager", name: "Castle Lager", description: null, price: 4000, subcategory: "Beer" },
    { id: "mi_beers_castle_lite", name: "Castle Lite", description: null, price: 4000, subcategory: "Beer" },
    { id: "mi_beers_serengeti_lite", name: "Serengeti Lite", description: null, price: 4000, subcategory: "Beer" },
    { id: "mi_beers_flying_fish", name: "Flying Fish", description: null, price: 4000, subcategory: "Beer" },
    { id: "mi_beers_kili_lager", name: "Kili Lager", description: null, price: 4000, subcategory: "Beer" },
    { id: "mi_beers_brutal", name: "Brutal", description: null, price: 5000, subcategory: "Beer" },
    { id: "mi_beers_heineken", name: "Heineken", description: null, price: 5000, subcategory: "Beer" },
    { id: "mi_beers_windhoek", name: "Windhoek", description: null, price: 5000, subcategory: "Beer" },
    { id: "mi_beers_desperado", name: "Desperado", description: null, price: 5000, subcategory: "Beer" },
    { id: "mi_beers_savana", name: "Savana", description: null, price: 5000, subcategory: "Beer" },
  ] },
  { id: "mcat_wines", name: "Wines", slug: "wines", type: "DRINK", revenueKind: "BAR", description: "Red, white, rosé and sparkling.", items: [
    { id: "mi_wines_st_anna", name: "St Anna", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_robertson_white", name: "Robertson White", description: null, price: 30000, subcategory: "Wine" },
    { id: "mi_wines_robertson_red", name: "Robertson Red", description: null, price: 30000, subcategory: "Wine" },
    { id: "mi_wines_drostdyhof_red_750ml", name: "Drostdyhof Red 750ML", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_drostdyhof_red_375ml", name: "Drostdyhof Red 375ML", description: null, price: 15000, subcategory: "Wine" },
    { id: "mi_wines_drostdyhof_white_750ml", name: "Drostdyhof White 750ML", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_drostdyhof_white_375ml", name: "Drostdyhof White 375ML", description: null, price: 15000, subcategory: "Wine" },
    { id: "mi_wines_altar_wine", name: "Altar Wine", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_pearly_bay_dry_rose", name: "Pearly Bay Dry Rose", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_pearly_bay_sweet", name: "Pearly Bay Sweet", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_lion_hill", name: "Lion Hill", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_four_cousin", name: "Four Cousin", description: null, price: 30000, subcategory: "Wine" },
    { id: "mi_wines_bonne_esperance", name: "Bonne Esperance", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_dodoma_wine", name: "Dodoma Wine", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_dompo", name: "Dompo", description: null, price: 25000, subcategory: "Wine" },
    { id: "mi_wines_champaign_pearly_bay", name: "Champaign Pearly Bay", description: null, price: 45000, subcategory: "Wine" },
    { id: "mi_wines_mohans", name: "Mohans", description: null, price: 25000, subcategory: "Wine" },
  ] },
  { id: "mcat_whiskies", name: "Whiskies", slug: "whiskies", type: "DRINK", revenueKind: "BAR", description: "Scotch, Irish and American whiskies by the bottle.", items: [
    { id: "mi_whiskies_jameson_750ml", name: "Jameson 750ML", description: null, price: 85000, subcategory: "Whisky" },
    { id: "mi_whiskies_jameson_500ml", name: "Jameson 500ML", description: null, price: 55000, subcategory: "Whisky" },
    { id: "mi_whiskies_jameson_250ml", name: "Jameson 250ML", description: null, price: 35000, subcategory: "Whisky" },
    { id: "mi_whiskies_grants_750ml", name: "Grants 750ML", description: null, price: 55000, subcategory: "Whisky" },
    { id: "mi_whiskies_grants_500ml", name: "Grants 500ML", description: null, price: 35000, subcategory: "Whisky" },
    { id: "mi_whiskies_ballantine_750ml", name: "Ballantine 750ML", description: null, price: 60000, subcategory: "Whisky" },
    { id: "mi_whiskies_ballantine_250ml", name: "Ballantine 250ML", description: null, price: 30000, subcategory: "Whisky" },
    { id: "mi_whiskies_jack_daniels_750ml", name: "Jack Daniels 750ML", description: null, price: 100000, subcategory: "Whisky" },
    { id: "mi_whiskies_jack_daniels_500ml", name: "Jack Daniels 500ML", description: null, price: 65000, subcategory: "Whisky" },
    { id: "mi_whiskies_jack_daniels_250ml", name: "Jack Daniels 250ML", description: null, price: 50000, subcategory: "Whisky" },
    { id: "mi_whiskies_red_label_750ml", name: "Red Label 750ML", description: null, price: 85000, subcategory: "Whisky" },
    { id: "mi_whiskies_red_label_250ml", name: "Red Label 250ML", description: null, price: 30000, subcategory: "Whisky" },
    { id: "mi_whiskies_black_label_750ml", name: "Black Label 750ML", description: null, price: 100000, subcategory: "Whisky" },
    { id: "mi_whiskies_black_white_750ml", name: "Black & White 750ML", description: null, price: 35000, subcategory: "Whisky" },
    { id: "mi_whiskies_black_white_250ml", name: "Black & White 250ML", description: null, price: 20000, subcategory: "Whisky" },
  ] },
  { id: "mcat_spirits", name: "Spirits", slug: "spirits", type: "DRINK", revenueKind: "BAR", description: "Cognac, vodka, gin, liqueurs and local favourites.", items: [
    { id: "mi_spirits_jagermeister_1l", name: "Jagermeister 1L", description: null, price: 120000, subcategory: "Spirit" },
    { id: "mi_spirits_jagermeister_750ml", name: "Jagermeister 750ML", description: null, price: 80000, subcategory: "Spirit" },
    { id: "mi_spirits_jagermeister_500ml", name: "Jagermeister 500ML", description: null, price: 45000, subcategory: "Spirit" },
    { id: "mi_spirits_jagermeister_250ml", name: "Jagermeister 250ML", description: null, price: 35000, subcategory: "Spirit" },
    { id: "mi_spirits_hennessy_750ml", name: "Hennessy 750ML", description: null, price: 200000, subcategory: "Spirit" },
    { id: "mi_spirits_hennessy_500ml", name: "Hennessy 500ML", description: null, price: 120000, subcategory: "Spirit" },
    { id: "mi_spirits_hennessy_250ml", name: "Hennessy 250ML", description: null, price: 60000, subcategory: "Spirit" },
    { id: "mi_spirits_konyagi_750ml", name: "Konyagi 750ML", description: null, price: 15000, subcategory: "Spirit" },
    { id: "mi_spirits_konyagi_500ml", name: "Konyagi 500ML", description: null, price: 10000, subcategory: "Spirit" },
    { id: "mi_spirits_konyagi_250ml", name: "Konyagi 250ML", description: null, price: 5000, subcategory: "Spirit" },
    { id: "mi_spirits_k_vant_750ml", name: "K-Vant 750ML", description: null, price: 15000, subcategory: "Spirit" },
    { id: "mi_spirits_k_vant_250ml", name: "K-Vant 250ML", description: null, price: 5000, subcategory: "Spirit" },
    { id: "mi_spirits_smirnoff_750ml", name: "Smirnoff 750ML", description: null, price: 55000, subcategory: "Spirit" },
    { id: "mi_spirits_smirnoff_250ml", name: "Smirnoff 250ML", description: null, price: 20000, subcategory: "Spirit" },
    { id: "mi_spirits_gordons_750ml", name: "Gordons 750ML", description: null, price: 50000, subcategory: "Spirit" },
    { id: "mi_spirits_gordons_250ml", name: "Gordons 250ML", description: null, price: 25000, subcategory: "Spirit" },
    { id: "mi_spirits_absolute_vodka_750ml", name: "Absolute Vodka 750ML", description: null, price: 70000, subcategory: "Spirit" },
    { id: "mi_spirits_absolute_vodka_500ml", name: "Absolute Vodka 500ML", description: null, price: 45000, subcategory: "Spirit" },
    { id: "mi_spirits_absolute_vodka_250ml", name: "Absolute Vodka 250ML", description: null, price: 40000, subcategory: "Spirit" },
    { id: "mi_spirits_jb_750ml", name: "JB 750ML", description: null, price: 60000, subcategory: "Spirit" },
    { id: "mi_spirits_jb_250ml", name: "JB 250ML", description: null, price: 30000, subcategory: "Spirit" },
    { id: "mi_spirits_hanson_choice_750ml", name: "Hanson Choice 750ML", description: null, price: 20000, subcategory: "Spirit" },
    { id: "mi_spirits_hanson_choice_250ml", name: "Hanson Choice 250ML", description: null, price: 7000, subcategory: "Spirit" },
    { id: "mi_spirits_camino", name: "Camino", description: null, price: 60000, subcategory: "Spirit" },
    { id: "mi_spirits_amarula_500ml", name: "Amarula 500ML", description: null, price: 35000, subcategory: "Spirit" },
    { id: "mi_spirits_amarula_750ml", name: "Amarula 750ML", description: null, price: 60000, subcategory: "Spirit" },
    { id: "mi_spirits_amarula_250ml", name: "Amarula 250ML", description: null, price: 22000, subcategory: "Spirit" },
  ] },
];
