import type { Locale } from "../config";
import type { Catalog } from "../translate";

/**
 * Translation bundles. Each area's strings live in their own file under catalog/<locale>/<bundle>/ (the bundle's
 * index.ts is generated by `npm run i18n:index`):
 *   common — shared pieces (ui kit, statuses, lib labels): everywhere
 *   public — the website, booking, QR ordering, guest pages: sent to customers' browsers
 *   staff  — the staff app and reports: sent to staff browsers
 *   server — messages made on the server (errors, WhatsApp, reports): never sent to a browser as a whole
 * English has no catalog — the English text is the key.
 */
export type Bundle = "common" | "public" | "staff" | "server";
export const ALL_BUNDLES: Bundle[] = ["common", "public", "staff", "server"];

const loaders: Record<Exclude<Locale, "en">, Record<Bundle, () => Promise<Catalog>>> = {
  "zh-CN": {
    common: () => import("./zh-CN/common").then((m) => m.default),
    public: () => import("./zh-CN/public").then((m) => m.default),
    staff: () => import("./zh-CN/staff").then((m) => m.default),
    server: () => import("./zh-CN/server").then((m) => m.default),
  },
};

const memo = new Map<string, Promise<Catalog>>();

/** The strings for these bundles, merged (common first; a later bundle wins on the same English). */
export function loadCatalog(locale: Locale, bundles: Bundle[]): Promise<Catalog> {
  if (locale === "en") return Promise.resolve({});
  const key = `${locale}:${bundles.join(",")}`;
  let p = memo.get(key);
  if (!p) {
    const set = loaders[locale];
    p = Promise.all(bundles.map((b) => set[b]())).then((parts) => Object.freeze(Object.assign({}, ...parts)) as Catalog);
    memo.set(key, p);
  }
  return p;
}
