// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrations (and the seed) use the DIRECT connection when one is given — Neon's pooled URL (DATABASE_URL, used by
  // the app at run time) cannot hold the lock `prisma migrate deploy` takes. Locally only DATABASE_URL is needed.
  datasource: {
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
