// Generated by `npm run i18n:check` — how much of the interface each language covers. Do not edit by hand.
export const COVERAGE: Record<string, { total: number; translated: number; missing: string[] }> = {
  "zh-CN": {
    "total": 11280,
    "translated": 11280,
    "missing": []
  }
};
