// Generated by `npm run i18n:index` — every area file in this folder, merged. Do not edit by hand.
import type { Catalog } from "../../../translate";
import m_fix_guest_apps_restaurant from "./fix-guest-apps-restaurant";
import m_fix_site_misc from "./fix-site-misc";
import m_fix_site_services_dining from "./fix-site-services-dining";
import m_guest_apps_ordering from "./guest-apps-ordering";
import m_guest_apps_restaurant from "./guest-apps-restaurant";
import m_hotel_qr from "./hotel-qr";
import m_orders_lang from "./orders-lang";
import m_site_booking_rooms from "./site-booking-rooms";
import m_site_kit_home from "./site-kit-home";
import m_site_pages_content from "./site-pages-content";
import m_site_pages_forms from "./site-pages-forms";
import m_site_services_dining from "./site-services-dining";
import m_site_shell from "./site-shell";
import m_stay_wifi from "./stay-wifi";
import m_svc_booking from "./svc-booking";

const catalog: Catalog = {
  ...m_fix_guest_apps_restaurant,
  ...m_fix_site_misc,
  ...m_fix_site_services_dining,
  ...m_guest_apps_ordering,
  ...m_guest_apps_restaurant,
  ...m_hotel_qr,
  ...m_orders_lang,
  ...m_site_booking_rooms,
  ...m_site_kit_home,
  ...m_site_pages_content,
  ...m_site_pages_forms,
  ...m_site_services_dining,
  ...m_site_shell,
  ...m_stay_wifi,
  ...m_svc_booking,
};
export default catalog;
