// Generated by `npm run i18n:index` — every area file in this folder, merged. Do not edit by hand.
import type { Catalog } from "../../../translate";
import m_content_admin from "./content-admin";
import m_dashboards from "./dashboards";
import m_finance from "./finance";
import m_fix_people_misc from "./fix-people-misc";
import m_groups_corporate from "./groups-corporate";
import m_guest_language from "./guest-language";
import m_guest_pages from "./guest-pages";
import m_guests_meeting from "./guests-meeting";
import m_hotelqr_transport from "./hotelqr-transport";
import m_inventory_misc from "./inventory-misc";
import m_invoices_requests from "./invoices-requests";
import m_money_desk from "./money-desk";
import m_orders_lang from "./orders-lang";
import m_reception_components from "./reception-components";
import m_reports_lang from "./reports-lang";
import m_reports_papers from "./reports-papers";
import m_reservation_detail from "./reservation-detail";
import m_reservation_new from "./reservation-new";
import m_restaurant_misc from "./restaurant-misc";
import m_restaurant_portal from "./restaurant-portal";
import m_restaurant_pos_waiter from "./restaurant-pos-waiter";
import m_restaurant_tables from "./restaurant-tables";
import m_rooms from "./rooms";
import m_settings_people from "./settings-people";
import m_shifts_requests from "./shifts-requests";
import m_staff_shell from "./staff-shell";
import m_stock_assets from "./stock-assets";
import m_svc_reporting from "./svc-reporting";

const catalog: Catalog = {
  ...m_content_admin,
  ...m_dashboards,
  ...m_finance,
  ...m_fix_people_misc,
  ...m_groups_corporate,
  ...m_guest_language,
  ...m_guest_pages,
  ...m_guests_meeting,
  ...m_hotelqr_transport,
  ...m_inventory_misc,
  ...m_invoices_requests,
  ...m_money_desk,
  ...m_orders_lang,
  ...m_reception_components,
  ...m_reports_lang,
  ...m_reports_papers,
  ...m_reservation_detail,
  ...m_reservation_new,
  ...m_restaurant_misc,
  ...m_restaurant_portal,
  ...m_restaurant_pos_waiter,
  ...m_restaurant_tables,
  ...m_rooms,
  ...m_settings_people,
  ...m_shifts_requests,
  ...m_staff_shell,
  ...m_stock_assets,
  ...m_svc_reporting,
};
export default catalog;
