// Generated by `npm run i18n:index` — every area file in this folder, merged. Do not edit by hand.
import type { Catalog } from "../../../translate";
import m_content from "./content";
import m_fix_svc_a from "./fix-svc-a";
import m_fix_svc_b from "./fix-svc-b";
import m_lib_labels from "./lib-labels";
import m_orders_lang from "./orders-lang";
import m_reports from "./reports";
import m_svc_booking from "./svc-booking";
import m_svc_misc from "./svc-misc";
import m_svc_money from "./svc-money";
import m_svc_online_pay from "./svc-online-pay";
import m_svc_ops from "./svc-ops";
import m_svc_reporting from "./svc-reporting";
import m_svc_reservations from "./svc-reservations";
import m_svc_restaurant from "./svc-restaurant";
import m_whatsapp from "./whatsapp";

const catalog: Catalog = {
  ...m_content,
  ...m_fix_svc_a,
  ...m_fix_svc_b,
  ...m_lib_labels,
  ...m_orders_lang,
  ...m_reports,
  ...m_svc_booking,
  ...m_svc_misc,
  ...m_svc_money,
  ...m_svc_online_pay,
  ...m_svc_ops,
  ...m_svc_reporting,
  ...m_svc_reservations,
  ...m_svc_restaurant,
  ...m_whatsapp,
};
export default catalog;
