#!/usr/bin/env node
// Translation catalog tooling.
//   node scripts/i18n.mjs index           — (re)write each bundle's index.ts from the area files next to it
//   node scripts/i18n.mjs check [--list]  — every English string marked in the code (t("…"), t.plural, t.rich, msg("…"))
//                                           that has no Chinese yet; placeholder mismatches; writes coverage.ts
//   node scripts/i18n.mjs missing <path…> — the untranslated strings used in these files/folders (for whoever works there)
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, basename } from "node:path";

const ROOT = decodeURIComponent(new URL("..", import.meta.url).pathname);
const SRC = join(ROOT, "src");
const CAT = join(SRC, "i18n", "catalog");
const LOCALES = ["zh-CN"];
const BUNDLES = ["common", "public", "staff", "server"];

const walk = (dir, out = []) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (name === "node_modules" || name === "generated" || name.startsWith(".")) continue;
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else if (/\.(tsx?|mjs)$/.test(name) && !/\.test\.tsx?$/.test(name)) out.push(p);
  }
  return out;
};

const ident = (s) => s.replace(/[^A-Za-z0-9_]/g, "_");

function writeIndexes() {
  for (const locale of LOCALES) {
    for (const b of BUNDLES) {
      const dir = join(CAT, locale, b);
      const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".ts") && f !== "index.ts").sort() : [];
      const imports = files.map((f) => `import ${ident("m_" + basename(f, ".ts"))} from "./${basename(f, ".ts")}";`).join("\n");
      const body = files.length ? `{\n${files.map((f) => `  ...${ident("m_" + basename(f, ".ts"))},`).join("\n")}\n}` : "{}";
      writeFileSync(join(dir, "index.ts"),
        `// Generated by \`npm run i18n:index\` — every area file in this folder, merged. Do not edit by hand.\nimport type { Catalog } from "../../../translate";\n${imports}${imports ? "\n" : ""}\nconst catalog: Catalog = ${body};\nexport default catalog;\n`);
    }
  }
}

// A JS string literal → its value.
const lit = (raw) => {
  const q = raw[0];
  const inner = raw.slice(1, -1);
  if (q === '"') return JSON.parse(raw);
  return JSON.parse(`"${inner.replace(/\\'/g, "'").replace(/\\`/g, "`").replace(/"/g, '\\"')}"`);
};
const STR = String.raw`"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'|\`(?:[^\`\\$]|\\.)*\``;

function readCatalog(locale) {
  const all = new Map();
  for (const b of BUNDLES) {
    const dir = join(CAT, locale, b);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir).filter((f) => f.endsWith(".ts") && f !== "index.ts")) {
      const text = readFileSync(join(dir, f), "utf8");
      const re = new RegExp(String.raw`^\s*(${STR})\s*:\s*(${STR})\s*,?\s*$`, "gm");
      let m;
      while ((m = re.exec(text))) all.set(lit(m[1]), { value: lit(m[2]), file: relative(ROOT, join(dir, f)) });
    }
  }
  return all;
}

function extract(files) {
  const keys = new Map();
  const add = (k, file) => {
    if (!k || !/[A-Za-z]/.test(k)) return;
    if (!keys.has(k)) keys.set(k, new Set());
    keys.get(k).add(relative(ROOT, file));
  };
  const call = new RegExp(String.raw`\bt(?:\.rich)?\(\s*(${STR})`, "g");
  const ctx = new RegExp(String.raw`\bt\.ctx\(\s*(${STR})\s*,\s*(${STR})`, "g");
  const plural = new RegExp(String.raw`\bt\.plural\([^,()]*(?:\([^()]*\))?[^,()]*,\s*(${STR})\s*,\s*(${STR})`, "g");
  const marker = new RegExp(String.raw`(?:\bmsgf?\(|new AppError\()\s*(${STR})`, "g");
  for (const f of files) {
    if (f.includes(`${join("src", "i18n")}`)) continue;
    const text = readFileSync(f, "utf8");
    let m;
    for (const re of [call, marker]) { re.lastIndex = 0; while ((m = re.exec(text))) { try { add(lit(m[1]), f); } catch {} } }
    ctx.lastIndex = 0;
    while ((m = ctx.exec(text))) { try { add(`${lit(m[1])}::${lit(m[2])}`, f); } catch {} }
    plural.lastIndex = 0;
    while ((m = plural.exec(text))) { try { add(lit(m[1]), f); add(lit(m[2]), f); } catch {} }
  }
  return keys;
}

const holes = (s) => [...s.matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort().join(",");
const tags = (s) => [...s.matchAll(/<(\w+)>/g)].map((m) => m[1]).sort().join(",");

const [cmd = "check", ...args] = process.argv.slice(2).filter((a) => !a.startsWith("--"));
const pathsOf = (list) => list.flatMap((a) => {
  const p = join(ROOT, a);
  return statSync(p).isDirectory() ? walk(p) : [p];
});
if (cmd === "index") {
  writeIndexes();
  console.log("i18n: indexes written");
} else {
  writeIndexes();
  const files = cmd === "missing" && args.length ? pathsOf(args) : walk(SRC);
  const keys = extract(files);
  let bad = 0;
  for (const locale of LOCALES) {
    const cat = readCatalog(locale);
    const missing = [...keys.keys()].filter((k) => !cat.has(k));
    const mismatched = [...cat].filter(([k, v]) => keys.has(k) && (holes(k) !== holes(v.value) || tags(k) !== tags(v.value)));
    console.log(`${locale}: ${keys.size} strings in the code · ${keys.size - missing.length} translated · ${missing.length} missing · ${mismatched.length} placeholder mismatches`);
    if (cmd === "missing" || process.argv.includes("--list")) for (const k of missing) console.log(`  MISSING ${JSON.stringify(k)}  ← ${[...keys.get(k)].slice(0, 2).join(", ")}`);
    for (const [k, v] of mismatched) console.log(`  MISMATCH ${JSON.stringify(k)} → ${JSON.stringify(v.value)} (${v.file})`);
    bad += mismatched.length;
    if (cmd === "check") {
      writeFileSync(join(SRC, "i18n", "coverage.ts"),
        `// Generated by \`npm run i18n:check\` — how much of the interface each language covers. Do not edit by hand.\nexport const COVERAGE: Record<string, { total: number; translated: number; missing: string[] }> = ${JSON.stringify({ [locale]: { total: keys.size, translated: keys.size - missing.length, missing: missing.slice(0, 200) } }, null, 2)};\n`);
    }
  }
  if (bad) process.exitCode = 1;
}
