// Generated by `npm run i18n:index` — every area file in this folder, merged. Do not edit by hand.
import type { Catalog } from "../../../translate";
import m_fix_desk_misc from "./fix-desk-misc";
import m_fix_svc_b from "./fix-svc-b";
import m_guest_apps_ordering from "./guest-apps-ordering";
import m_lib_labels from "./lib-labels";
import m_order_requests from "./order-requests";
import m_ui_kit from "./ui-kit";

const catalog: Catalog = {
  ...m_fix_desk_misc,
  ...m_fix_svc_b,
  ...m_guest_apps_ordering,
  ...m_lib_labels,
  ...m_order_requests,
  ...m_ui_kit,
};
export default catalog;
